### ISSUE TITLE
PA Review: Hosting on Heroku

### ISSUE THREAD

**Issue by Alspirid** [Alspirid/Lounge-search#2]
- [x]  Initial push!
- [x]  Production deployment push!

**Comment by evhumphrey** [comment]
Reopened because when you turn it in, you need to make sure it's production ready on Heroku (so this issue will be a reminder)

We have a reading on this, but includes:

 Remove all console.logs
 Remove everything from window
 Remove Redux logger
https://github.com/appacademy/curriculum/blob/master/full-stack-project/resources/helpful_tools/production-ready.md

**Comment by Alspirid** [comment]
I've completed the final deployment
